# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
fail_fast: true
repos:
  - repo: https://github.com/psf/black
    rev: 21.5b1
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.3.0
    hooks:
      - id: prettier
        files: ^frontend/
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v7.26.0
    hooks:
      - id: eslint
        args:
          - --max-warnings=0
        files: \.[jt]sx?$  # *.js, *.jsx, *.ts and *.tsx
        exclude: node_modules
        types: [ file ]
        additional_dependencies:
          - "@typescript-eslint/eslint-plugin"
          - "@typescript-eslint/parser"
          - eslint-config-prettier
          - eslint-plugin-prettier
