# Generated by Django 2.2.1 on 2019-05-10 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0004_auto_20190507_1728"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="first_name",
            field=models.CharField(blank=True, max_length=1023),
        ),
    ]
