# Generated by Django 3.0.6 on 2020-05-29 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="person",
            options={"verbose_name_plural": "People"},
        ),
    ]
