name: "Dev CI/CD"
on:
  push:
    branches-ignore:
      - $default-branch
  pull_request:
    branches:
      - $default-branch
env:
  SECRET_KEY: astupidsecretjusttogetcicdworking
jobs:
  build-lint-test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ 3.6, 3.7, 3.8 ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Check Linting/Formatting
        run: |
          black --check .
          flake8 --extend-exclude venv/
      - name: Run Tests
        run: |
          python manage.py test
