name: "Deploy"
on: workflow_dispatch
env:
  DEFAULT_BRANCH: master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy Warning
        if: ${{ github.ref != refs/heads/$DEFAULT_BRANCH }}
        run: |
          echo "::error ::Cannot deploy from non-default branch ${{ github.ref }}"
          exit 1
      - name: Deploy to Heroku
        if: ${{ github.ref == refs/heads/$DEFAULT_BRANCH }}
        uses: akhileshns/heroku-deploy@v3.8.8
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "booktracker-hayes"
          heroku_email: "zrev2220@gmail.com"
